Refactoring as advised by @zero2one
digipolisgent/openbib-id-api pull request #1
Opened 2017-01-17 15:15 UTC by Jelle-S

2017-01-17 15:16 UTC, Jelle-S commented
Not really a lot I can do about the codeclimate check fails I think

2017-01-17 16:51 UTC, daften approved these changes
Schoon :) Geen opmerkingen

2017-01-18 08:16 UTC, zero2one requested changes

2017-01-18 08:16 UTC, zero2one commented on src/Auth/Credentials.php
> +
No empty line between opening brace `{` and first method.

> **Is a remark for all classes.**

2017-01-18 08:16 UTC, zero2one commented on src/Auth/Environment.php
> +        return new self('https://mijn.bibliotheek.be/openbibid/rest', 'prod');
Use `static`:

```php
return new static(...);
```

2017-01-18 08:16 UTC, zero2one commented on src/Auth/Environment.php
> +        return new self('https://staging-mijn.bibliotheek.be/openbibid/rest', 'staging');
Use `static`:

```php
return new static(...);
```

2017-01-18 08:16 UTC, zero2one commented on src/Auth/Environment.php
> +
1 empty line between methods (instead of 2).

2017-01-18 08:16 UTC, zero2one commented on src/Auth/EnvironmentInterface.php
> +
1 empty line between methods (instead of 2).

2017-01-18 08:16 UTC, zero2one commented on src/Consumer/BibConsumer.php
> +
1 empty line between parameters and methods (instead of 2).

2017-01-18 08:16 UTC, zero2one commented on src/Service/LibraryService.php
> +class LibraryService extends Service implements LibraryServiceInterface
Niet nodig om ook nog eens "implements LibraryServiceInterface" toe te voegen; Is reeds gebeurd door de Service class.

2017-01-18 08:16 UTC, zero2one commented on src/Service/ListService.php
> +class ListService extends Service implements ListServiceInterface
Niet nodig om ook nog eens "implements LibraryServiceInterface" toe te voegen; Is reeds gebeurd door de Service class.

2017-01-18 08:16 UTC, zero2one commented on src/Service/ListServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed. 

Indien een exception getrhowed wordt door het aanroepen van een andere methode of methode van ander object dan dient deze niet in de dochead gedocumenteerd te worden.

2017-01-18 08:16 UTC, zero2one commented on src/Service/ListServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:16 UTC, zero2one commented on src/Service/ListServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:16 UTC, zero2one commented on src/Service/ListServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:16 UTC, zero2one commented on src/Service/OnlineCollectionServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:16 UTC, zero2one commented on src/Service/OnlineCollectionServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:16 UTC, zero2one commented on src/Service/OnlineCollectionServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:16 UTC, zero2one commented on src/Service/OnlineCollectionServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:16 UTC, zero2one commented on src/Service/OnlineCollectionServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:16 UTC, zero2one commented on src/Service/UserServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:16 UTC, zero2one commented on src/Service/UserServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:16 UTC, zero2one commented on src/Service/UserServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:16 UTC, zero2one commented on src/Service/UserServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:16 UTC, zero2one commented on src/Service/UserServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:16 UTC, zero2one commented on src/Service/UserServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:16 UTC, zero2one commented on src/Service/UserServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:16 UTC, zero2one commented on src/Service/UserServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:16 UTC, zero2one commented on src/Service/UserServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:16 UTC, zero2one commented on src/Service/UserServiceInterface.php
> +     * @throws BibApi\Exception\BibException
@throws moet enkel toegevoegd worden in de documentatie als de methode zelf een exception throwed.

2017-01-18 08:18 UTC, Jelle-S commented on src/Service/LibraryService.php
> +class LibraryService extends Service implements LibraryServiceInterface
nee: Service implements ServiceInterface
LibraryService implements LibraryServiceInterface (= service om bibliotheken op te halen)

2017-01-18 08:19 UTC, Jelle-S commented on src/Service/ListService.php
> +class ListService extends Service implements ListServiceInterface
nee: Service implements ServiceInterface
ListService implements **List**ServiceInterface (= service om lijsten op te halen)

2017-01-18 08:20 UTC, zero2one requested changes

2017-01-18 08:20 UTC, zero2one commented on src/Storage/FileStorage.php
No extra empty line between last method and closing brace.

2017-01-18 08:20 UTC, zero2one commented on src/Storage/FileStorage.php
> +           unlink($key);
One more space (12 spaces instead of 11).

2017-01-18 08:20 UTC, zero2one commented on src/Storage/SessionStorage.php
Remove empty line between last method and closing brace.

2017-01-18 08:21 UTC, Jelle-S commented on src/Auth/Environment.php
> +        return new self('https://mijn.bibliotheek.be/openbibid/rest', 'prod');
waarom static? Wanneer iemand overerft van Environment, willen we dan niet dat ze deze methode kunnen gebruiker zonder ze expliciet te moeten overschrijven?

2017-01-18 08:24 UTC, zero2one commented on src/Service/ListService.php
> +class ListService extends Service implements ListServiceInterface
ok

2017-01-18 11:03 UTC, zero2one approved these changes

2017-01-18 11:05 UTC, merged